[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "rpi-lgpio>=0.6"
]

[project]
name = "temper"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
dependencies = [
  "rpi-lgpio>=0.6"
]

[project.scripts]
temper = "temper:main"

[tool.basedpyright]
extraPaths = ["."]
useLibraryCodeForTypes = true
reportMissingTypeStubs = "none"
ignore = [
  "typings",
  "nix/store",
  ".direnv"
]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "**/.venv",
  "**/.*"
]
venvPath = "."
venv = ".venv"
