#ifndef TEMPER_CONSTANTS_H_
#define TEMPER_CONSTANTS_H_

#define PULSE_WIDTH_THRESHOLD_US 45
#define MAX_TIMINGS 85
#define DHT11_PIN 25
#define LED_PIN 26
#define TEMP_THRESHOLD_C 30
#define LOOP_TIMEOUT_MS 1000

#endif
