#ifndef TEMPER_CONSTANTS_H_
#define TEMPER_CONSTANTS_H_

#define PULSE_WIDTH_THRESHOLD_US 45
#define POLL_COUNTER_THRESHOLD 16
#define MAX_TIMINGS 85
#define DHT11_PIN 25
#define LED_PIN 24
#define TEMP_THRESHOLD_C 30
#define LOOP_TIMEOUT_MS 1000

#define MAX_TIME_FOR_ZERO_BIT_US 28
#define MAX_TIME_FOR_ONE_BIT_US 70
#define MAX_TIME_BUFFER 10
#define BITS_PER_BYTE 8
#define TOTAL_BITS_PER_READ 40
#define RESPONSE_TIME_US 80
#define PRE_BIT_DELAY 50

#define MAXIMUM_TEMPERATURE_READINGS 10
#define TEMPERATURE_THRESHOLD_CELSIUS 26.0

#endif
